### ISSUE TITLE
Issues since php7.1 with Opcache

### ISSUE THREAD

**Issue by trsteel88** [ezyang/htmlpurifier#135] opened 2017-06-01 05:56 UTC
I'm having issues since php7.1 where the process consumes too many resources and eventually gets killed. It's like it gets stuck in a loop.

Tried running the latest tag versioned and master without success.

Was hoping that #108 would solve the problem.

Can only get it to succeed if Opcache is disabled.

Is anyone else having this problem?

**Comment by trsteel88** [comment] 2017-06-01 05:57
Fyi, this is failing on php7.1.4 and php7.1.5

**Comment by trsteel88** [comment] 2017-06-01 06:33
Could be similar to #135. I'm not using any custom config. Just the defaults.

**Comment by trsteel88** [comment] 2017-06-01 06:34
Could be similar to #134. I'm not using any custom config. Just the defaults.

**Comment by ezyang** [comment] 2017-06-01 13:03
I think this is probably #134, but I'll keep it open so that it's easier for people to find. We think it's a PHP regression.

**Comment by Xiphin** [comment] 2017-06-01 13:38
It seems to be fixed by me: https://github.com/Xiphin/htmlpurifier/commit/cb4871f4464659918e0c59b914d359a8874ea62a

**Comment by trsteel88** [comment] 2017-06-01 23:29
@Xiphin that fixed the problem. However, it doesn't need to be a stdClass. It also works with making it null instead of false. If would be more efficient to not create an unnecessary class.

Not sure why?

**Comment by trsteel88** [comment] 2017-06-01 23:32
I've submitted a PR to use null instead. Are you able to take a look and tag that as a version if you're happy with it @ezyang? Thanks.

**Comment by Xiphin** [comment] 2017-06-02 01:04
@trsteel88 我当时没有考虑太多，觉得 $current_li 在此处就是个对象 object，所以就直接 new stdClass。想了一下还是 null 比较好点。(However, I didn't think too much at that time. I thought $current_li was an object here, so I directly used new stdClass. Think about it, or is it better to use null.)

**Comment by trsteel88** [comment] 2017-06-02 03:23
If it's not false it is defined as a new object within the statement. Null works here and doesn't result in an unwanted object.

**Comment by ezyang** [comment] 2017-06-03 01:10
Thanks @trsteel88 for the improvements!

**Closed by ezyang** 2017-06-03 01:10 UTC
