### ISSUE TITLE
How to use htmlpurifer in Laravel 5

### ISSUE THREAD

**Issue by euclid1990** [ezyang/htmlpurifier#75] opened 2016-02-19 10:44 UTC
In **Laravel 5**, To use this library, I have to install it via composer: All library files is put in `project_folder/vendor/ezyang/htmlpurifier/library/HTMLPurifier.auto.php`
And use below command in each class:
```
require_once app_path() . '/../vendor/ezyang/htmlpurifier/library/HTMLPurifier.auto.php';
```
Have a better than this way ?

Thank you !

Note: app_path() function return: `project_folder/app`
My web struct:
```
-- project_folder
---- app
---- vendor
-------- ezyang
------------ ...
```

**Comment by mbeech** [comment] 2016-02-19 23:17
Take a look at https://github.com/mewebstudio/Purifier

**Comment by ezyang** [comment] 2016-03-02 10:07
Closing this as not a bug in core HTML Purifier.

**Closed by ezyang** 2016-03-02 10:07 UTC

**Comment by chenwenbo123** [comment] 2018-11-02 09:14
thanks
