### ISSUE TITLE
Class HTMLPurifier_Language_en_x_test does not comply with psr-0 autoloading standard

### ISSUE THREAD

**Issue by xpetter** [ezyang/htmlpurifier#246] opened 2020-03-10 16:23 UTC
I get this from composer:
Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185

**Comment by ricardomartos** [comment] 2020-03-11 08:36
Same here

**Comment by cap-akimrey** [comment] 2020-03-12 20:28
Same Composer notice here, but citing psr-4 non-compliance:
Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185

**Comment by maxxscho** [comment] 2020-03-13 14:19
Same here with PSR-0 non compliance:

```
Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
```

**Comment by tgfarias** [comment] 2020-03-17 16:15
`Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201`
Same here

**Comment by sebastiansulinski** [comment] 2020-03-18 16:05
And here.

**Comment by lphilps** [comment] 2020-03-19 18:44
It appears that the problem is that the class name
"HTMLPurifier_Language_en_x_test"
doesn't match the file name
"en-x-test.php".

Composer v1.10.0 started producing this error, previous versions of composer didn't care.

Any chance of getting a new release that fixes this?

**Comment by ezyang** [comment] 2020-03-20 14:52
We should probably just delete this file and the tests associated with it.

**Comment by maxxscho** [comment] 2020-03-21 15:02
Since there aren't any tests in this file, I guess nobody will miss it 😄

**Comment by roelofr** [comment] 2020-04-16 14:34
The file isn't a test, it's used for a test though.

https://github.com/ezyang/htmlpurifier/blob/b81690c17eae5dbea7557d1f359af8dd17e9beef/tests/HTMLPurifier/LanguageFactoryTest.php#L37-L38

The `HTMLPurifier_LanguageFactoryTest` should be re-written to use a dev-only response, which would remove the file from autoloading.

**Comment by kghbln** [comment] 2020-04-19 10:17
Will be cool to get rid of this warning. People are already starting to duplicate this issue here.

**Comment by Jimbolino** [comment] 2020-04-27 01:54
The problem was actually fixed some time ago: https://github.com/ezyang/htmlpurifier/commit/4faca32a4d4b8152d17956606e1fb5043fcc1f10

Maybe it's time for a new v4.13.0 release, because most people require a stable version in their projects

**Comment by roelofr** [comment] 2020-04-27 01:59
In my tests Composer will still throw the warning, despite excluding them from the classmap (I don't know why, seems weird to me).

**Comment by Jimbolino** [comment] 2020-04-27 02:05
I think you are trying to exclude files that are part of vendor/ezyang/htmlpurifier.
With me the errors disappeared when i switched my dependecy from "^4.7" to "dev-master"

**Comment by roelofr** [comment] 2020-04-27 02:45
Hmm, could be. I was replying from the top of my head.

A tag is absolutely a good idea.

**Comment by williamdes** [comment] 2020-04-27 07:33
https://github.com/ezyang/htmlpurifier/blob/master/.gitattributes could be used to exclude the file from composer vendor bundles
But fixing the real issue is the best option.

**Comment by jbdelhommeau** [comment] 2020-06-19 07:33
Bug will be fixed with this commit : https://github.com/ezyang/htmlpurifier/commit/4faca32a4d4b8152d17956606e1fb5043fcc1f10 the 31 Oct 2019 juste after the laster release 28 Oct 2019.

 Can you release a new version to fix it please !?

**Comment by roelofr** [comment] 2020-06-21 21:08
Basically everyone is waiting for a tag.

**Comment by jbdelhommeau** [comment] 2020-06-25 12:51
Poke @ezyang !

**Comment by ezyang** [comment] 2020-06-29 01:09
4.13.0 is tagged and released

**Closed by ezyang** 2020-06-29 01:09 UTC
